source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'NiceLittleDemo' do
  pod 'Alamofire', '~> 4.4'
  pod 'SDWebImage', '~> 4.0'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NiceLittleDemo

  target 'NiceLittleDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NiceLittleDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
